controller_manager:
  ros__parameters:
    update_rate: 50

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    base_frame_id: base_link
    left_wheel_names: ["left_wheel_front_joint", "left_wheel_back_joint"]
    right_wheel_names: ["right_wheel_front_joint", "right_wheel_back_joint"]
    wheel_separation: 1.17  # Odległość między kołami
    wheel_radius: 0.26  # Promień kół
    publish_rate: 50.0  # Częstotliwość publikowania danych
    enable_odom_tf: true  # Włączanie transformacji TF dla odometrii
    use_stamped_vel: false  # Używanie znaczników czasu dla prędkości
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 10.0
        min_velocity: -10.0
        has_acceleration_limits: true
        max_acceleration: 3.0
        min_acceleration: -3.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        min_velocity: -3.0
        has_acceleration_limits: true
        max_acceleration: 2.0
        min_acceleration: -2.0